
default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/development.sqlite3
.
test:
  <<: *default
  database: rails_citly_bb_test


production:
  <<: *default
  database: db/production.sqlite3

